version: '3'
services:
  db:
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=final_project_db
      - MYSQL_USER=final_project
      - MYSQL_PASSWORD=Brock2003!
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
    volumes:
      - "./db:/docker-entrypoint-initdb.d"

  www:
    image: php:apache
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "./:/var/www/html"
    ports:
      - 80:80
      - 443:443
    depends_on:
      - composer
      - db
      - phpmyadmin

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8001:80
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306

  composer:
    image: composer:latest
    volumes:
      - "./:/app"
    working_dir: /app
    command: install
